### ISSUE TITLE
0(0) : error C7528: OpenGL reserves names containing '__'

### ISSUE THREAD

**Issue by therontarigo** [mzucker/st_glfw#1]
Running st_glfw gives the error `0(0) : error C7528: OpenGL reserves names containing '__'`
Easily fixed by replacing all `__iFinalScale` -> `_stglfw_iFinalScale`  (I avoided `_st_` naming convention since Shadertoy itself might someday use something similar, I have no idea).

**Comment by mzucker** [comment]
Fixed in e1fc6da
